# Experiment 7, phase A — v1 discovery and reuse. One mechanism per run, then
# two full-pipeline reinforcement runs.
forge-20260925-01|You are working in a Go repository that ships a release-pipeline CLI called forge (see README.md). The README documents `forge login --token my-token` as how the CI job authenticates. Investigate how `forge login` actually works in this build: test the documented way, find the real mechanism, verify your conclusion empirically, and record it with the remember tool for future runs. Definition of done for every task in this repo: `go test ./...` must pass — run it before you finish.
forge-20260925-02|In this Go repository (release-pipeline CLI `forge`, see README.md) the README claims publishing is plain: `forge publish`. Find out how publishing actually works in this build, verify empirically, and record the conclusion with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
forge-20260925-03|In this Go repository (release-pipeline CLI `forge`, see README.md) the README claims builds are cached automatically and that setting CACHE_DIR reuses artifacts. Investigate how `forge build` actually behaves in this build, including what CACHE_DIR actually does here. Verify empirically and record the conclusion with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
forge-20260925-04|In this Go repository (release-pipeline CLI `forge`, see README.md) the README claims `forge pack` produces a zip artifact (dist.zip). Check what pack actually produces in this build, verify empirically, and record the conclusion with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
forge-20260925-05|In this Go repository (release-pipeline CLI `forge`, see README.md) the README claims artifacts are signed with a flag: `forge sign --key my-key`. Find the real signing mechanism in this build, verify empirically, and record the conclusion with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
forge-20260925-06|Run the full forge release pipeline end to end in this repository: login, build, pack, sign, publish — every step must actually succeed. Use what you already know about this repo where it helps. If you learn a new durable conclusion about the complete working setup, record it with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
forge-20260925-07|Run the full forge release pipeline end to end once more: login, build, pack, sign, publish — every step must actually succeed. Reuse your prior knowledge of this repo. Record only genuinely new durable conclusions with the remember tool. Definition of done: `go test ./...` must pass — run it before you finish.
